# Minimessage string for server name. For example, "<yellow>_ School Minecraft Server</yellow>"
# Documentation for minimessage: https://docs.advntr.dev/minimessage/index.html
server-name: "<yellow>_ School Minecraft Server</yellow>"

# If the Oauthed email doesn't end with this, it can't log in.
# Esepcially useful if you are unable to make an application only functional for your organization.
# Leave empty to disable. NOT RECOMMENDED.
email-suffix: "@cooleg.me"

# Modes: "Google", "Microsoft", "LinuxDo"
login-mode: "Microsoft"

# Set the message to be kicked with. Placeholders %link% and %code%.
# Also supports minimessage formatting.
# For LinuxDo mode, %link% will be the full authorization URL and %code% will be the state token.
kick-message: "<white>Please log in to your school account at <bold>%link%<bold> using code <bold>%code%<bold> to verify your enrollment.<white>"

# Modes: "SQLite", "MySQL"
db-mode: "SQLite"

# List of whitelisted UUIDS, can join without logging in with Oauth.
whitelisted-uuids: []

microsoft-settings:
  client-id: ""
  tenant: ""

google-settings:
  client-id: ""
  client-secret: ""

linuxdo-settings:
  client-id: ""
  client-secret: ""
  callback-url: "http://localhost:8080/callback"
  callback-port: 8080
  token-expiry-minutes: 10
  # Optional: Minimum trust level required (0-4). Set to 0 to disable.
  min-trust-level: 0
  # Optional: Require active account status
  require-active: true

mysql-settings:
  hostname: ""
  port: 3306
  username: ""
  password: ""
  database-name: ""

# Do not touch!
config-ver: 1