name: OauthMC
version: '${project.version}'
main: me.cooleg.oauthmc.OauthMC
api-version: '1.18'
author: TrollsterCooleg
description: Plugin to authenticate players logging in through Google or Microsoft.